CREATE TYPE "public"."billing_frequency" AS ENUM('monthly', 'yearly');--> statement-breakpoint
CREATE TYPE "public"."delivery_method" AS ENUM('api', 'sftp', 'email');--> statement-breakpoint
CREATE TABLE "string-trial_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "string-trial_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "string-trial_feed" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	"base_price" numeric NOT NULL
);
--> statement-breakpoint
CREATE TABLE "string-trial_organization_to_feed" (
	"id" serial PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	"feed_id" integer NOT NULL,
	"organization_id" integer NOT NULL,
	"access_until" timestamp with time zone NOT NULL,
	"dashboard_url" varchar(255),
	"delivery_method" "delivery_method",
	"delivery_config" jsonb,
	"success_emails" text[],
	"fail_emails" text[],
	"schema_update_emails" text[],
	"billing_amount" numeric NOT NULL,
	"billing_frequency" "billing_frequency",
	CONSTRAINT "string-trial_organization_to_feed_feed_id_organization_id_unique" UNIQUE("feed_id","organization_id")
);
--> statement-breakpoint
CREATE TABLE "string-trial_organization" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	"billing_email" varchar(255) NOT NULL,
	"status" varchar(50) DEFAULT 'active' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "string-trial_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "string-trial_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "string-trial_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "string-trial_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "string-trial_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "string-trial_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "string-trial_account" ADD CONSTRAINT "string-trial_account_userId_string-trial_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."string-trial_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "string-trial_organization_to_feed" ADD CONSTRAINT "string-trial_organization_to_feed_feed_id_string-trial_feed_id_fk" FOREIGN KEY ("feed_id") REFERENCES "public"."string-trial_feed"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "string-trial_organization_to_feed" ADD CONSTRAINT "string-trial_organization_to_feed_organization_id_string-trial_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."string-trial_organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "string-trial_post" ADD CONSTRAINT "string-trial_post_createdById_string-trial_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."string-trial_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "string-trial_session" ADD CONSTRAINT "string-trial_session_userId_string-trial_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."string-trial_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "string-trial_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "org_feed_org_idx" ON "string-trial_organization_to_feed" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "org_feed_feed_idx" ON "string-trial_organization_to_feed" USING btree ("feed_id");--> statement-breakpoint
CREATE INDEX "org_name_idx" ON "string-trial_organization" USING btree ("name");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "string-trial_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "string-trial_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "string-trial_session" USING btree ("userId");